import * as THREE from 'three';
import type { InputManager } from '../core/InputManager';
import { PLANTS } from '../data/plants';
import { createPlantMarker, createPortal, createTree } from '../world/WorldFactory';
import type { ThreeStage } from './ThreeStage';

export class ForestScene {
  private player=new THREE.Group();
  private markers:{id:string;group:THREE.Group}[]=[];
  private portal=new THREE.Group();
  private onNearby: (plantId?:string,atPortal?:boolean)=>void=()=>{};
  constructor(private stage:ThreeStage,private input:InputManager){}
  enter(onNearby:(plantId?:string,atPortal?:boolean)=>void):void{this.onNearby=onNearby;const s=this.stage.scene;this.stage.clear();this.markers=[];s.background=new THREE.Color(0x11172a);s.fog=new THREE.FogExp2(0x18253a,.045);const ground=new THREE.Mesh(new THREE.PlaneGeometry(34,34),new THREE.MeshStandardMaterial({color:0x203a30,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;s.add(ground);for(let i=0;i<30;i++){const a=Math.random()*Math.PI*2,r=5+Math.random()*10;s.add(createTree(Math.cos(a)*r,Math.sin(a)*r,.7+Math.random()*.65));}const positions=[[-3,-1],[2,-3],[3.5,2.2]];PLANTS.forEach((plant,i)=>{const group=createPlantMarker(Number.parseInt(plant.accent.slice(1),16));group.position.set(positions[i][0],0,positions[i][1]);s.add(group);this.markers.push({id:plant.id,group});});this.portal=createPortal();this.portal.scale.setScalar(.55);this.portal.position.set(0,0,-6);this.portal.rotation.y=Math.PI;s.add(this.portal);const body=new THREE.Mesh(new THREE.CapsuleGeometry(.25,.65,5,8),new THREE.MeshStandardMaterial({color:0x593b72,roughness:.8}));body.position.y=.72;body.castShadow=true;const hat=new THREE.Mesh(new THREE.ConeGeometry(.48,.85,12),new THREE.MeshStandardMaterial({color:0x2e234a}));hat.position.y=1.55;hat.rotation.z=-.16;this.player=new THREE.Group();this.player.add(body,hat);s.add(this.player);s.add(new THREE.HemisphereLight(0x7695c8,0x152318,2.1));const moon=new THREE.DirectionalLight(0xbcd8ff,2.4);moon.position.set(-4,9,5);moon.castShadow=true;s.add(moon);this.stage.camera.position.set(0,7,8);this.stage.camera.lookAt(0,0,0);this.stage.setUpdater((dt,t)=>this.update(dt,t));}
  private update(dt:number,t:number):void{const m=this.input.update(),length=Math.hypot(m.x,m.y)||1;this.player.position.x+=m.x/length*dt*3.2;this.player.position.z-=m.y/length*dt*3.2;this.player.position.x=THREE.MathUtils.clamp(this.player.position.x,-6.5,6.5);this.player.position.z=THREE.MathUtils.clamp(this.player.position.z,-6.5,6.5);this.player.position.y=Math.abs(Math.sin(t*5))*.03;this.markers.forEach(({group},i)=>{group.rotation.y=t*.35+i;group.position.y=Math.sin(t*1.8+i)*.05;});const nearest=this.markers.map(m=>({id:m.id,d:m.group.position.distanceTo(this.player.position)})).sort((a,b)=>a.d-b.d)[0];const portalDistance=this.portal.position.distanceTo(this.player.position);this.onNearby(nearest?.d<1.35?nearest.id:undefined,portalDistance<1.7);this.stage.camera.position.x+=(this.player.position.x-this.stage.camera.position.x)*.035;this.stage.camera.position.z+=(this.player.position.z+8-this.stage.camera.position.z)*.035;this.stage.camera.lookAt(this.player.position.x,0,this.player.position.z);}
}
