import * as THREE from 'three';

const mat=(color:number,roughness=.85)=>new THREE.MeshStandardMaterial({color,roughness});
export const createPortal=():THREE.Group=>{const g=new THREE.Group();const stone=mat(0x544e68);for(let i=0;i<11;i++){const a=Math.PI*(i/10);const mesh=new THREE.Mesh(new THREE.DodecahedronGeometry(.34,0),stone);mesh.position.set(Math.cos(a)*2,Math.sin(a)*2,0);mesh.scale.set(.8,1.35,.7);mesh.castShadow=true;g.add(mesh);}const core=new THREE.Mesh(new THREE.CircleGeometry(1.66,48),new THREE.MeshBasicMaterial({color:0x73e2d0,transparent:true,opacity:.42,side:THREE.DoubleSide}));core.position.z=-.05;g.add(core);const inner=new THREE.Mesh(new THREE.RingGeometry(1.42,1.56,48),new THREE.MeshBasicMaterial({color:0xf0d38b,transparent:true,opacity:.8,side:THREE.DoubleSide}));g.add(inner);return g;};
export const createTree=(x:number,z:number,scale=1):THREE.Group=>{const g=new THREE.Group();const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.18,.3,2.7,7),mat(0x493b37));trunk.position.y=1.35;trunk.castShadow=true;g.add(trunk);for(let i=0;i<3;i++){const crown=new THREE.Mesh(new THREE.ConeGeometry(1.25-i*.2,1.9,7),mat(0x274b3c));crown.position.y=2.6+i*.65;crown.castShadow=true;g.add(crown);}g.position.set(x,0,z);g.scale.setScalar(scale);return g;};
export const createPlantMarker=(color:number):THREE.Group=>{const g=new THREE.Group();const stem=new THREE.Mesh(new THREE.CylinderGeometry(.035,.055,.75,6),mat(0x5a8b57));stem.position.y=.38;g.add(stem);for(let i=0;i<6;i++){const petal=new THREE.Mesh(new THREE.SphereGeometry(.16,10,7),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.35}));const a=i/6*Math.PI*2;petal.scale.set(.65,1.5,.45);petal.position.set(Math.cos(a)*.16,.86,Math.sin(a)*.16);petal.rotation.z=-a;g.add(petal);}const glow=new THREE.PointLight(color,1.3,3);glow.position.y=.8;g.add(glow);return g;};

export const createClueWisps=(color:number):THREE.Group=>{const group=new THREE.Group();for(let i=0;i<5;i++){const wisp=new THREE.Mesh(new THREE.SphereGeometry(.035+i*.008,7,7),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.8}));const angle=i/5*Math.PI*2;wisp.position.set(Math.cos(angle)*(.55+i*.08),.35+i*.16,Math.sin(angle)*(.55+i*.08));group.add(wisp);}return group;};

export const createLandmark=(type:'pool'|'stones'|'fallen-log'):THREE.Group=>{const group=new THREE.Group();if(type==='pool'){const pool=new THREE.Mesh(new THREE.CircleGeometry(1.25,32),new THREE.MeshStandardMaterial({color:0x31586b,emissive:0x203b58,emissiveIntensity:.65,roughness:.25}));pool.rotation.x=-Math.PI/2;pool.position.y=.015;group.add(pool);}if(type==='fallen-log'){const log=new THREE.Mesh(new THREE.CylinderGeometry(.28,.38,3.2,8),mat(0x4a352c));log.rotation.z=Math.PI/2;log.position.y=.32;group.add(log);}if(type==='stones'){for(let i=0;i<6;i++){const stone=new THREE.Mesh(new THREE.DodecahedronGeometry(.28+Math.random()*.15,0),mat(0x596267));const a=i/6*Math.PI*2;stone.position.set(Math.cos(a)*.9,.2,Math.sin(a)*.9);group.add(stone);}}return group;};
